/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ComposedAllOfInlineValidation
 */
public class ComposedAllOfInlineValidationTest {
    private final ComposedAllOfInlineValidation model = new ComposedAllOfInlineValidation();

    /**
     * Model tests for ComposedAllOfInlineValidation
     */
    @Test
    public void testComposedAllOfInlineValidation() {
        // TODO: test ComposedAllOfInlineValidation
    }

}
