/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ComposedAnyOfInlineValidation
 */
public class ComposedAnyOfInlineValidationTest {
    private final ComposedAnyOfInlineValidation model = new ComposedAnyOfInlineValidation();

    /**
     * Model tests for ComposedAnyOfInlineValidation
     */
    @Test
    public void testComposedAnyOfInlineValidation() {
        // TODO: test ComposedAnyOfInlineValidation
    }

}
