/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ObjectWithValidationsInArrayPropItems
 */
public class ObjectWithValidationsInArrayPropItemsTest {
    private final ObjectWithValidationsInArrayPropItems model = new ObjectWithValidationsInArrayPropItems();

    /**
     * Model tests for ObjectWithValidationsInArrayPropItems
     */
    @Test
    public void testObjectWithValidationsInArrayPropItems() {
        // TODO: test ObjectWithValidationsInArrayPropItems
    }

    /**
     * Test the property 'arrayProp'
     */
    @Test
    public void arrayPropTest() {
        // TODO: test arrayProp
    }

}
