/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ObjectModelWithAddPropsInProps
 */
public class ObjectModelWithAddPropsInPropsTest {
    private final ObjectModelWithAddPropsInProps model = new ObjectModelWithAddPropsInProps();

    /**
     * Model tests for ObjectModelWithAddPropsInProps
     */
    @Test
    public void testObjectModelWithAddPropsInProps() {
        // TODO: test ObjectModelWithAddPropsInProps
    }

    /**
     * Test the property 'mapWithAdditionalPropertiesUnset'
     */
    @Test
    public void mapWithAdditionalPropertiesUnsetTest() {
        // TODO: test mapWithAdditionalPropertiesUnset
    }

    /**
     * Test the property 'mapWithAdditionalPropertiesTrue'
     */
    @Test
    public void mapWithAdditionalPropertiesTrueTest() {
        // TODO: test mapWithAdditionalPropertiesTrue
    }

    /**
     * Test the property 'mapWithAdditionalPropertiesFalse'
     */
    @Test
    public void mapWithAdditionalPropertiesFalseTest() {
        // TODO: test mapWithAdditionalPropertiesFalse
    }

    /**
     * Test the property 'mapWithAdditionalPropertiesSchema'
     */
    @Test
    public void mapWithAdditionalPropertiesSchemaTest() {
        // TODO: test mapWithAdditionalPropertiesSchema
    }

}
