/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * ObjectModelWithRefAddPropsInProps
 */
@JsonPropertyOrder({
  ObjectModelWithRefAddPropsInProps.JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_UNSET,
  ObjectModelWithRefAddPropsInProps.JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_TRUE,
  ObjectModelWithRefAddPropsInProps.JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_FALSE,
  ObjectModelWithRefAddPropsInProps.JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_SCHEMA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ObjectModelWithRefAddPropsInProps {
  public static final String JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_UNSET = "map_with_additional_properties_unset";
  private Object mapWithAdditionalPropertiesUnset;

  public static final String JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_TRUE = "map_with_additional_properties_true";
  private Map<String, Object> mapWithAdditionalPropertiesTrue = null;

  public static final String JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_FALSE = "map_with_additional_properties_false";
  private Object mapWithAdditionalPropertiesFalse;

  public static final String JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_SCHEMA = "map_with_additional_properties_schema";
  private Map<String, String> mapWithAdditionalPropertiesSchema = null;


  public ObjectModelWithRefAddPropsInProps mapWithAdditionalPropertiesUnset(Object mapWithAdditionalPropertiesUnset) {
    this.mapWithAdditionalPropertiesUnset = mapWithAdditionalPropertiesUnset;
    return this;
  }

   /**
   * Get mapWithAdditionalPropertiesUnset
   * @return mapWithAdditionalPropertiesUnset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_UNSET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMapWithAdditionalPropertiesUnset() {
    return mapWithAdditionalPropertiesUnset;
  }


  public void setMapWithAdditionalPropertiesUnset(Object mapWithAdditionalPropertiesUnset) {
    this.mapWithAdditionalPropertiesUnset = mapWithAdditionalPropertiesUnset;
  }


  public ObjectModelWithRefAddPropsInProps mapWithAdditionalPropertiesTrue(Map<String, Object> mapWithAdditionalPropertiesTrue) {
    this.mapWithAdditionalPropertiesTrue = mapWithAdditionalPropertiesTrue;
    return this;
  }

  public ObjectModelWithRefAddPropsInProps putMapWithAdditionalPropertiesTrueItem(String key, Object mapWithAdditionalPropertiesTrueItem) {
    if (this.mapWithAdditionalPropertiesTrue == null) {
      this.mapWithAdditionalPropertiesTrue = new HashMap<>();
    }
    this.mapWithAdditionalPropertiesTrue.put(key, mapWithAdditionalPropertiesTrueItem);
    return this;
  }

   /**
   * Get mapWithAdditionalPropertiesTrue
   * @return mapWithAdditionalPropertiesTrue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_TRUE)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMapWithAdditionalPropertiesTrue() {
    return mapWithAdditionalPropertiesTrue;
  }


  public void setMapWithAdditionalPropertiesTrue(Map<String, Object> mapWithAdditionalPropertiesTrue) {
    this.mapWithAdditionalPropertiesTrue = mapWithAdditionalPropertiesTrue;
  }


  public ObjectModelWithRefAddPropsInProps mapWithAdditionalPropertiesFalse(Object mapWithAdditionalPropertiesFalse) {
    this.mapWithAdditionalPropertiesFalse = mapWithAdditionalPropertiesFalse;
    return this;
  }

   /**
   * Get mapWithAdditionalPropertiesFalse
   * @return mapWithAdditionalPropertiesFalse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_FALSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMapWithAdditionalPropertiesFalse() {
    return mapWithAdditionalPropertiesFalse;
  }


  public void setMapWithAdditionalPropertiesFalse(Object mapWithAdditionalPropertiesFalse) {
    this.mapWithAdditionalPropertiesFalse = mapWithAdditionalPropertiesFalse;
  }


  public ObjectModelWithRefAddPropsInProps mapWithAdditionalPropertiesSchema(Map<String, String> mapWithAdditionalPropertiesSchema) {
    this.mapWithAdditionalPropertiesSchema = mapWithAdditionalPropertiesSchema;
    return this;
  }

  public ObjectModelWithRefAddPropsInProps putMapWithAdditionalPropertiesSchemaItem(String key, String mapWithAdditionalPropertiesSchemaItem) {
    if (this.mapWithAdditionalPropertiesSchema == null) {
      this.mapWithAdditionalPropertiesSchema = new HashMap<>();
    }
    this.mapWithAdditionalPropertiesSchema.put(key, mapWithAdditionalPropertiesSchemaItem);
    return this;
  }

   /**
   * Get mapWithAdditionalPropertiesSchema
   * @return mapWithAdditionalPropertiesSchema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAP_WITH_ADDITIONAL_PROPERTIES_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMapWithAdditionalPropertiesSchema() {
    return mapWithAdditionalPropertiesSchema;
  }


  public void setMapWithAdditionalPropertiesSchema(Map<String, String> mapWithAdditionalPropertiesSchema) {
    this.mapWithAdditionalPropertiesSchema = mapWithAdditionalPropertiesSchema;
  }


  /**
   * Return true if this ObjectModelWithRefAddPropsInProps object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectModelWithRefAddPropsInProps objectModelWithRefAddPropsInProps = (ObjectModelWithRefAddPropsInProps) o;
    return Objects.equals(this.mapWithAdditionalPropertiesUnset, objectModelWithRefAddPropsInProps.mapWithAdditionalPropertiesUnset) &&
        Objects.equals(this.mapWithAdditionalPropertiesTrue, objectModelWithRefAddPropsInProps.mapWithAdditionalPropertiesTrue) &&
        Objects.equals(this.mapWithAdditionalPropertiesFalse, objectModelWithRefAddPropsInProps.mapWithAdditionalPropertiesFalse) &&
        Objects.equals(this.mapWithAdditionalPropertiesSchema, objectModelWithRefAddPropsInProps.mapWithAdditionalPropertiesSchema);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mapWithAdditionalPropertiesUnset, mapWithAdditionalPropertiesTrue, mapWithAdditionalPropertiesFalse, mapWithAdditionalPropertiesSchema);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectModelWithRefAddPropsInProps {\n");
    sb.append("    mapWithAdditionalPropertiesUnset: ").append(toIndentedString(mapWithAdditionalPropertiesUnset)).append("\n");
    sb.append("    mapWithAdditionalPropertiesTrue: ").append(toIndentedString(mapWithAdditionalPropertiesTrue)).append("\n");
    sb.append("    mapWithAdditionalPropertiesFalse: ").append(toIndentedString(mapWithAdditionalPropertiesFalse)).append("\n");
    sb.append("    mapWithAdditionalPropertiesSchema: ").append(toIndentedString(mapWithAdditionalPropertiesSchema)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

