/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdditionalPropertiesApi
 */
public class AdditionalPropertiesApiTest {

    private final AdditionalPropertiesApi api = new AdditionalPropertiesApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void arrayWithValidationsInItems2Test() throws ApiException {
        //Object additionalPropertiesUnset = null;
        //Map<String, Object> additionalPropertiesTrue = null;
        //Object additionalPropertiesFalse = null;
        //Map<String, String> additionalPropertiesSchema = null;
        //Object response = api.arrayWithValidationsInItems2(additionalPropertiesUnset, additionalPropertiesTrue, additionalPropertiesFalse, additionalPropertiesSchema);
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void arrayWithValidationsInItemsRefTest() throws ApiException {
        //Object additionalPropertiesUnset = null;
        //Map<String, Object> additionalPropertiesTrue = null;
        //Object additionalPropertiesFalse = null;
        //Map<String, String> additionalPropertiesSchema = null;
        //Object response = api.arrayWithValidationsInItemsRef(additionalPropertiesUnset, additionalPropertiesTrue, additionalPropertiesFalse, additionalPropertiesSchema);
        // TODO: test validations
    }

}
