/*
 * OpenAPI Petstore
 * sample spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.*;
import org.openapitools.client.auth.*;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void arrayWithValidationsInItemsTest() throws ApiException {
        //List<Long> items = null;
        //List<Long> requestBody = null;
        //List<Long> response = api.arrayWithValidationsInItems(items, requestBody);
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refArrayWithValidationsInItemsTest() throws ApiException {
        //List<Long> items = null;
        //List<Long> requestBody = null;
        //List<Long> response = api.refArrayWithValidationsInItems(items, requestBody);
        // TODO: test validations
    }

}
